version: "3.5"

services:
  postgres:
    image: postgres:latest
    container_name: db
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: pass
    networks:
      - test

  keycloak:
    image: jboss/keycloak
    container_name: keycloak
    restart: always
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_PASSWORD: pass
      #KEYCLOAK_USER: john
      #KEYCLOAK_PASSWORD: secret
    depends_on:
      - postgres
    ports:
      - 8088:8080
    networks:
      - test

volumes:
  postgres_data:

networks:
  test:
    #driver: bridge
    #ipam:
     # config:
      #  - subnet: 172.5.0.0/16
    name: test_net