version: '3.9'

volumes:
  postgres_data:
     

services:
  postgres:
      image: postgres
      container_name: db
      restart: always
      volumes:
        - postgres_data:/var/lib/postgresql/data
      environment:
        POSTGRES_DB: keycloak
        POSTGRES_USER: keycloak
        POSTGRES_PASSWORD: password
      networks:
        - test

  keycloak:
      image: jboss/keycloak
      container_name: keycloak
      restart: always
      environment:
        DB_VENDOR: POSTGRES
        DB_ADDR: postgres
        DB_DATABASE: keycloak
        DB_USER: keycloak
        DB_SCHEMA: public
        DB_PASSWORD: password
        #KEYCLOAK_USER: admin
        #KEYCLOAK_PASSWORD: admin 
        

      ports:
        - 8088:8080
      depends_on:
        - postgres
      networks:
        - test

  api:
    image: api:latest
    build: .
    container_name: api
    ports:
      - "5000:5000"
    networks:
      - test
    volumes:
      - ./app:/app
    environment:
      #KEYCLOAK_URI: http://keycloak:8088/auth/
      REALM: myRealm
      CLIENT_ID: flask-app
      CLIENT_SECRET: ""
      OPENID_URL: http://localhost:8088/auth/realms/myRealm/protocol/openid-connect
      #PROXY_ADDRESS_FORWARDING: true
      #ADMIN_USER: admin
      #ADMIN_PASS: admin     

networks:
  test:
    #driver: bridge
    #ipam:
      #config:
       # - subnet: 172.17.0.0/16
    name: test_net  

