version: '3.9'

volumes:
  postgres_data:

services:
  postgres:
      image: postgres
      container_name: db
      #restart: always
      volumes:
        - postgres_data:/var/lib/postgresql/data
      environment:
        POSTGRES_DB: keycloak
        POSTGRES_USER: keycloak
        POSTGRES_PASSWORD: password
      networks:
        - test

  keycloak:
      image: jboss/keycloak
      container_name: keycloak
      #restart: always
      environment:
        DB_VENDOR: POSTGRES
        DB_ADDR: postgres
        DB_DATABASE: keycloak
        DB_USER: keycloak
        DB_PASSWORD: password
        KEYCLOAK_USER: head
        KEYCLOAK_PASSWORD: pass
        #JDBC_PARAMS: "ssl=true"
        #SSL-REQUIRED: "none"
        
      ports:
        - 8088:8080
        - 8443:8443
      volumes:
        
      depends_on:
        - postgres
      networks:
        - test



networks:
  test:
    #driver: bridge
    #ipam:
      #config:
       # - subnet: 172.17.0.0/16
    name: test_net     