version: '3.9'

volumes:
  postgres_data:
     

services:
  postgres:
      image: postgres
      container_name: db
      restart: always
      volumes:
        - postgres_data:/var/lib/postgresql/data
      environment:
        POSTGRES_DB: keycloak
        POSTGRES_USER: keycloak
        POSTGRES_PASSWORD: password
      networks:
        - test

  keycloak:
      image: jboss/keycloak
      container_name: keycloak
      restart: always
      environment:
        DB_VENDOR: POSTGRES
        DB_ADDR: postgres
        DB_DATABASE: keycloak
        DB_USER: keycloak
        DB_SCHEMA: public
        DB_PASSWORD: password
        KEYCLOAK_USER: admin
        KEYCLOAK_PASSWORD: admin      

      ports:
        - 8088:8080
      depends_on:
        - postgres
      networks:
        - test

  api:
    image: api
    build: .
    container_name: api
    ports:
      - "5000:5000"
    networks:
      - test
    volumes:
      - ./new_task3:/app
    environment:
      KEYCLOAK_URI: http://keycloak:8088/auth/
      REALM: myapp
      CLIENT_ID: Test_cli
      CLIENT_SECRET: a79ddce0-08b6-4b26-b2d5-96a09cefe67a
      OPENID_URL: http://keycloak:8088/auth/realms/myRealm/protocol/openid-connect
      #ADMIN_USER: admin
      #ADMIN_PASS: admin     

networks:
  test:
    #driver: bridge
    #ipam:
      #config:
       # - subnet: 172.17.0.0/16
    name: test_net  

